"""inital migration

Revision ID: 2c84d6702625
Revises: a42ee04cc6ba
Create Date: 2019-11-26 13:56:59.524690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c84d6702625'
down_revision = 'a42ee04cc6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('example_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'examples', ['example_id'], ['id'])
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'example_id')
    # ### end Alembic commands ###
