"""initial migration

Revision ID: 5621368f5c4b
Revises: 945c8faaca7e
Create Date: 2019-11-25 16:09:31.982029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5621368f5c4b'
down_revision = '945c8faaca7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comments', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.add_column('Comments', sa.Column('pitch_title', sa.String(), nullable=True))
    op.drop_column('Comments', 'movie_id')
    op.drop_column('Comments', 'movie_title')
    op.drop_column('Comments', 'image_path')
    op.add_column('pitches', sa.Column('content', sa.String(), nullable=True))
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('pitches', 'content')
    op.add_column('Comments', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Comments', sa.Column('movie_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Comments', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Comments', 'pitch_title')
    op.drop_column('Comments', 'pitch_id')
    # ### end Alembic commands ###
