"""initial migration

Revision ID: a42ee04cc6ba
Revises: 81665337e09b
Create Date: 2019-11-26 09:00:42.040429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42ee04cc6ba'
down_revision = '81665337e09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_title', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('users_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['users_id'], ['id'])
    op.drop_column('comments', 'user_id')
    op.add_column('pitches', sa.Column('users_id', sa.Integer(), nullable=True))
    op.drop_constraint('pitches_user_id_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'users', ['users_id'], ['id'])
    op.drop_column('pitches', 'user_id')
    op.add_column('users', sa.Column('users_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'password_secure',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.create_foreign_key(None, 'users', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('users', 'password_secure',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('users', 'users_id')
    op.add_column('pitches', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_user_id_fkey', 'pitches', 'users', ['user_id'], ['id'])
    op.drop_column('pitches', 'users_id')
    op.add_column('comments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    op.drop_column('comments', 'users_id')
    op.drop_column('comments', 'pitch_title')
    # ### end Alembic commands ###
