"""initial migration

Revision ID: a52f7d491bb1
Revises: 7355020146c6
Create Date: 2019-11-25 22:54:21.925697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52f7d491bb1'
down_revision = '7355020146c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examples_name'), 'examples', ['name'], unique=False)
    op.drop_column('comments', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_examples_name'), table_name='examples')
    op.drop_table('examples')
    # ### end Alembic commands ###
